[package]
name = "rokit"
description = "Toolchain manager for Roblox projects"
version = "0.0.0"
license = "MIT"
edition = "2021"
repository = "https://github.com/filiptibell/rokit"
readme = "README.md"

[dependencies]
const_format = "0.2"
dashmap = { version = "5.5", features = ["serde"] }
dirs = "5.0"
octocrab = "0.36"
secrecy = "0.8"
semver = { version = "1.0", features = ["serde"] }
tempfile = "3.3"
thiserror = "1.0"
url = "2.5"
zip = "0.6"

# Async / runtime dependencies

async-signal = "0.2"
futures = "0.3"
http = "1.1"
http-body-util = "0.1"
tokio = { version = "1.36", features = ["full"] }
tracing = "0.1"

# Serde / file format dependencies

serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_with = { version = "3.7", features = ["macros"] }
toml_edit = "0.22"

# CLI dependencies

anyhow = { optional = true, version = "1.0" }
clap = { optional = true, version = "4.5", features = ["derive"] }
console = { optional = true, version = "0.15" }
dialoguer = { optional = true, version = "0.11" }
indicatif = { optional = true, version = "0.17" }
tracing-subscriber = { optional = true, version = "0.3", features = [
    "env-filter",
] }

[features]
default = ["cli"]
cli = [
    "dep:anyhow",
    "dep:clap",
    "dep:console",
    "dep:dialoguer",
    "dep:indicatif",
    "dep:tracing-subscriber",
]

[[bin]]
name = "rokit"
path = "src/main.rs"

[lib]
name = "rokit"
path = "lib/lib.rs"
