[package]
name = "aftman"
description = "Aftman is a command line toolchain manager"
version = "0.2.7"
license = "MIT"
edition = "2021"
repository = "https://github.com/LPGhatguy/aftman"
readme = "README.md"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]

[dependencies]
anyhow = "1.0"
atty = "0.2"
clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.11"
dirs = "5.0"
env_logger = "0.11"
fs-err = "2.8"
itertools = "0.12"
log = "0.4"
once_cell = "1.9"
reqwest = { version = "0.12", default-features = false, features = [
    "blocking",
    "rustls-tls",
] }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.3"
toml = "0.8"
toml_edit = "0.22"
zip = "0.6"

[target.'cfg(windows)'.dependencies]
command-group = "1.0.8"
winreg = "0.10.1"

[target.'cfg(unix)'.dependencies]
tokio = { version = "1.18.2", features = ["macros", "sync", "process"] }
signal-hook = "0.3.14"
