[package]
name = "aftman"
description = "Aftman is a command line toolchain manager"
version = "0.2.7"
license = "MIT"
edition = "2021"
repository = "https://github.com/LPGhatguy/aftman"
readme = "README.md"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
default-run = "aftman-new"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.11"
dirs = "5.0"
futures = "0.3"
itertools = "0.12"
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "http2",
] }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "3.7", features = ["macros"] }
tempfile = "3.3"
thiserror = "1.0"
tokio = { version = "1.36", features = ["full"] }
toml = "0.8"
toml_edit = "0.22"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zip = "0.6"

[target.'cfg(windows)'.dependencies]
command-group = "1.0"
winreg = "0.10"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3"

[[bin]]
name = "aftman"
path = "src/main.rs"

[[bin]]
name = "aftman-new"
path = "src-new/main.rs"

[lib]
name = "aftman"
path = "src-new/lib.rs"
