[package]
name = "aftman"
description = "Aftman, the prodigal sequel to Foreman"
license = "MIT"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/LPGhatguy/aftman"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
