name: CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [stable, 1.58.0]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      run: rustup default ${{ matrix.rust_version }}

    - name: Build
      run: cargo build --locked --verbose

    - name: Test
      run: cargo test --locked --verbose

  lint:
    name: Rustfmt and Clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      run: rustup default stable

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy
